/**
 * generated by Xtext
 */
package com.lowcoupling.mdpm.lng.rml.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class RMLDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
