/**
 * generated by Xtext
 */
package com.lowcoupling.mdpm.lng.rml.ui.contentassist;

import com.lowcoupling.mdpm.lng.rml.ui.contentassist.AbstractRMLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class RMLProposalProvider extends AbstractRMLProposalProvider {
}
