/*
 * generated by Xtext
 */
package com.lowcoupling.mdpm.lng.rml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RMLUiModule extends com.lowcoupling.mdpm.lng.rml.ui.AbstractRMLUiModule {
	public RMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
