/*
* generated by Xtext
*/
package com.lowcoupling.mdpm.lng.rml.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.lowcoupling.mdpm.lng.rml.services.RMLGrammarAccess;

public class RMLParser extends AbstractContentAssistParser {
	
	@Inject
	private RMLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.lowcoupling.mdpm.lng.rml.ui.contentassist.antlr.internal.InternalRMLParser createParser() {
		com.lowcoupling.mdpm.lng.rml.ui.contentassist.antlr.internal.InternalRMLParser result = new com.lowcoupling.mdpm.lng.rml.ui.contentassist.antlr.internal.InternalRMLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getREQNodeAccess().getAlternatives(), "rule__REQNode__Alternatives");
					put(grammarAccess.getREQPackageAccess().getGroup(), "rule__REQPackage__Group__0");
					put(grammarAccess.getREQRequirementAccess().getGroup(), "rule__REQRequirement__Group__0");
					put(grammarAccess.getModelAccess().getPackagesAssignment(), "rule__Model__PackagesAssignment");
					put(grammarAccess.getREQPackageAccess().getNameAssignment_1(), "rule__REQPackage__NameAssignment_1");
					put(grammarAccess.getREQPackageAccess().getPackageAssignment_3(), "rule__REQPackage__PackageAssignment_3");
					put(grammarAccess.getREQPackageAccess().getRequirementsAssignment_4(), "rule__REQPackage__RequirementsAssignment_4");
					put(grammarAccess.getREQRequirementAccess().getNameAssignment_1(), "rule__REQRequirement__NameAssignment_1");
					put(grammarAccess.getREQRequirementAccess().getTextAssignment_2(), "rule__REQRequirement__TextAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.lowcoupling.mdpm.lng.rml.ui.contentassist.antlr.internal.InternalRMLParser typedParser = (com.lowcoupling.mdpm.lng.rml.ui.contentassist.antlr.internal.InternalRMLParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public RMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
