/**
 * generated by Xtext
 */
package com.lowcoupling.mdpm.lng.rml.validation;

import com.lowcoupling.mdpm.lng.rml.validation.AbstractRMLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class RMLValidator extends AbstractRMLValidator {
}
