/*
 * generated by Xtext
 */
package com.lowcoupling.mdpm.lng.rml.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.lowcoupling.mdpm.lng.rml.ui.internal.RMLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RMLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RMLActivator.getInstance().getInjector(RMLActivator.COM_LOWCOUPLING_MDPM_LNG_RML_RML);
	}
	
}
