/*
* generated by Xtext
*/
package com.lowcoupling.mdpm.lng.rml;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RMLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.lowcoupling.mdpm.lng.rml.ui.internal.RMLActivator.getInstance().getInjector("com.lowcoupling.mdpm.lng.rml.RML");
	}
	
}
