/*
 * generated by Xtext
 */
package com.lowcoupling.mdpm.lng.rml;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RMLRuntimeModule extends com.lowcoupling.mdpm.lng.rml.AbstractRMLRuntimeModule {

}
